- project:
    templates:
      - check-requirements
      - tempest-plugin-jobs
      - manila-tempest-plugin-jobs-using-service-image
    queue: manila
    check:
      jobs:
        - manila-tempest-plugin-dummy-no-dhss
        - manila-tempest-plugin-dummy-dhss
        - manila-tempest-plugin-lvm-2025.1
        - manila-tempest-plugin-lvm-2024.2
        - manila-tempest-plugin-lvm-2024.1
        - manila-tempest-plugin-dummy-no-dhss-rbac
        - manila-tempest-plugin-container:
            voting: false
    gate:
      jobs:
        - manila-tempest-plugin-dummy-no-dhss
        - manila-tempest-plugin-dummy-dhss
