- project:
    templates:
      - check-requirements
      - tempest-plugin-jobs
      - manila-tempest-plugin-jobs-using-service-image
    queue: manila
    check:
      jobs:
        - manila-tempest-plugin-dummy-no-dhss
        - manila-tempest-plugin-dummy-dhss
        - manila-tempest-plugin-lvm-yoga
        - manila-tempest-plugin-lvm-xena
        - manila-tempest-plugin-lvm-wallaby
        - manila-tempest-plugin-dummy-no-dhss-rbac
        - manila-tempest-plugin-container:
            voting: false
        - manila-tempest-plugin-glusterfs-nfs:
            voting: false
    gate:
      jobs:
        - manila-tempest-plugin-dummy-no-dhss
        - manila-tempest-plugin-dummy-dhss
    experimental:
      jobs:
        - manila-tempest-plugin-glusterfs-native:
            voting: false
